name: OSS Hygiene

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: detect --redact --report-format sarif --report-path gitleaks.sarif
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: gitleaks.sarif

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [node, python]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
      
      - name: Install & test (Node)
        if: matrix.language == 'node'
        run: |
          npm ci
          npm run lint
          npm run typecheck
          npm test --if-present
      
      - name: Setup Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'
      
      - name: Install & test (Python)
        if: matrix.language == 'python'
        run: |
          pip install -r requirements.txt
          pip install -e .
          pytest -q tests || true

  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: github/codeql-action/init@v3
        with: 
          languages: 'javascript,python'
      - uses: actions/checkout@v4
      - uses: github/codeql-action/analyze@v3